# Problem Set 1 - Intro to Julia

**Author:** Gabriel Petrini

**Date:** September 1st, 2020

Directions: Answer all questions. Each student must turn in their own copy, but you may work in groups. Clearly label all answers. Show all of your code. Turn in jl-file(s), output files and writeup via GitHub. Your writeup may simply consist of comments in jl-file(s). If applicable, put the names of all group members at the top of your writeup or jl-file.

Before starting, you will need to install and load the following packages:
~~~
JLD2

Random

LinearAlgebra

Statistics
    
CSV

DataFrames

FreqTables 

Distributions
~~~

In [1]:
using Random, Statistics, FreqTables, Distributions;
using LinearAlgebra;
using CSV, DataFrames, JLD2;

Random.seed!(1234); # Setting seed

## Initializing variables and practice with basic matrix operations

###  Create the following four matrices of random numbers, setting the seed to '1234'. Name the matrices and set the dimensions as noted

a. $A_{10×7}$ - random numbers distributed $U [−5, 10]$
 

In [2]:
A = rand(Uniform(-5,10), 10,7)

10×7 Array{Float64,2}:
  3.86267    4.73323    9.25748    8.96673   -4.30567    4.88222    4.65556
  6.50196   -4.83641    9.47005    1.58408    5.47533    2.73441    1.02131
  3.49356   -4.00365    9.18663   -1.29706    0.476641  -1.08927    2.87586
  1.90128    9.3513     6.84856   -4.82271   -0.462833   3.93281    4.18015
  6.91039    4.70036    7.31741   -4.30936    0.588632  -0.613077   1.48865
  7.8122    -3.31271   -4.4876     2.44253   -2.74238   -0.671302  -3.76689
 -1.99121   -0.859686  -3.58183    5.98001   -2.79006    4.2724    -2.01413
 -0.520786   4.77496   -0.276107  -0.514137  -0.74898    4.9639     3.64123
 -1.29744   -4.15036   -3.08285    1.73773    1.07429    6.30262   -1.72734
  3.69508    7.6407     0.612801   8.12644    2.49296   -4.44674    0.430533

b. $B_{10×7}$ - random numbers distributed $N (−2, 15)$ [st dev is 15]

In [5]:
B = rand(Normal(-2, 15), 10, 7)

10×7 Array{Float64,2}:
   0.73882    -13.0124    -16.717    …    7.79041     6.69775     2.32697
  28.953        1.89506    -6.7458       -0.435064    1.57426   -21.9375
 -23.2179     -17.7292      1.98614       9.12677    33.5317     55.6956
   0.0171313    0.994137   13.9842      -15.2981     -3.50657    10.5644
 -13.2563     -14.1017     18.7752       23.56       -2.90555    -6.87955
   0.561669     0.967062   -0.80073  …   -8.90916     4.44054    -6.97473
 -25.7738     -19.3299    -14.5005       18.7093    -16.2828     30.492
 -31.625       10.2806     -8.6487       -1.82674    10.2093    -12.6817
  -0.853731     0.269651  -26.9484       -9.83497    11.2862    -16.57
   9.99003     16.7085     -9.81844      -8.42817     0.690528  -11.5884

c. $C_{5×7}$ - the first 5 rows and first 5 columns of $A$ and the last two columns and first 5 rows of $B$

In [19]:
C = [A[1:5, 1:5] B[1:5, -2:end:-1]] #TODO Check latter

BoundsError: BoundsError: attempt to access 10×7 Array{Float64,2} at index [1:5, -2:7:-2]

d. $D_{10×7}$ - where $D_{i, j} = A_{i, j}$ if $A_{i, j} \leq 0$, or $0$ otherwise


In [30]:
D .= A
D[A .> 0] .= 0
D

10×7 Array{Float64,2}:
  0.0        0.0        0.0        0.0       -4.30567    0.0        0.0
  0.0       -4.83641    0.0        0.0        0.0        0.0        0.0
  0.0       -4.00365    0.0       -1.29706    0.0       -1.08927    0.0
  0.0        0.0        0.0       -4.82271   -0.462833   0.0        0.0
  0.0        0.0        0.0       -4.30936    0.0       -0.613077   0.0
  0.0       -3.31271   -4.4876     0.0       -2.74238   -0.671302  -3.76689
 -1.99121   -0.859686  -3.58183    0.0       -2.79006    0.0       -2.01413
 -0.520786   0.0       -0.276107  -0.514137  -0.74898    0.0        0.0
 -1.29744   -4.15036   -3.08285    0.0        0.0        0.0       -1.72734
  0.0        0.0        0.0        0.0        0.0       -4.44674    0.0

##  Use a built-in Julia function to list the number of elements of A

In [37]:
function list_A()
    n = length(A)
    return println("The number of elements of A is ", n)
end
list_A()


The number of elements of A is 70


### Use a series of built-in Julia functions to list the number of unique elements of $D$

In [40]:
unique(D) |> length

29

### Using the reshape() function, create a new matrix called $E$ which is the 'vec' operator applied to $B$. Can you find an easier way to accomplish this?

In [44]:
E = reshape(B, (length(B),1))

70×1 Array{Float64,2}:
   0.7388198935443135
  28.95298708966839
 -23.217921470798856
   0.017131326864824103
 -13.256307606620506
   0.5616691925916748
 -25.773824342292993
 -31.62500743990568
  -0.8537306155079312
   9.990027487986394
 -13.012420762526913
   1.8950595152946734
 -17.729166348967837
   ⋮
  11.286229586575026
   0.6905276245415259
   2.3269734336374963
 -21.937512354780477
  55.69559764497001
  10.564413073741656
  -6.879553462102997
  -6.974732388028951
  30.491999873019076
 -12.68171738101507
 -16.570011717567688
 -11.58844094728918

### Create a new array called $F$ which is 3-dimensional and contains $A$ in the first column of the third dimension and $B$ in the second column of the third dimension


In [57]:
F = zeros(2, size(A))
F[:,:,1] = A

MethodError: MethodError: no method matching zeros(::Int64, ::Tuple{Int64,Int64})
Closest candidates are:
  zeros(!Matched::Union{Integer, AbstractUnitRange}...) at array.jl:499
  zeros(!Matched::Type{T}, ::Tuple{Vararg{Integer,N}}) where {T, N} at array.jl:504
  zeros(!Matched::Type{T}, ::Tuple{Vararg{Union{Integer, Base.OneTo},N}}) where {T, N} at array.jl:502

In [72]:
F = Array{Float64,3}
#F[:,:,1] .= A

Array{Float64,3}